version: '2.3'
services:
  db:
    container_name: dcopyright_db
    image: postgres:10.3
    ports:
    - "5432:5432"
    volumes:
      - /Users/benedict/documents/code/Docker/Dcopyright/data:/var/lib/postgresql/data
  app:
    container_name: dcopyright_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_dev
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: foreman start -f Procfile.dev -p 3000
    volumes:
    - .:/dcopyright
    - type: tmpfs
      target: /dcopyright/tmp/pids/
    ports:
    - "3000:3000"
    - "35729:35729"
    depends_on:
    - db