version: '2.3'
services:
  db:
    container_name: dcopyright_db
    image: postgres:10.3
    volumes:
#      - .:/data:/var/lib/postgresql/data
     - /Users/benedict/documents/code/Docker/DCopyright/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: dcopyright_app
    env_file:
      - .env_prod
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dcopyright
    ports:
      - "3000:3000"
  web:
    container_name: dcopyright_web
    env_file:
      - .env_prod
    links:
      - app
    build:
      context: .
      dockerfile: config/containers/Dockerfile-nginx
    volumes_from:
      - app
    ports:
      - "80:80"