default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password:  <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dcopyright_development

test:
  <<: *default
  database: dcopyright_test

production:
  <<: *default
  database: dcopyright_production
  username: dcopyright

